CREATE TABLE IF NOT EXISTS medical_provisions (
    id BIGSERIAL PRIMARY KEY,

    -- Regulatory document
    document_code TEXT NOT NULL,
    document_name TEXT NOT NULL,

    -- Stable identifier generated by ingestion.
    --
    -- Examples:
    -- MDR_ARTICLE_20
    -- MDR_ARTICLE_51
    -- MDR_ANNEX_VIII_RULE_8
    -- MDR_ANNEX_VIII_RULE_10
    provision_id TEXT NOT NULL,

    -- Broad provision category.
    --
    -- Examples:
    -- definition
    -- article
    -- classification_rule
    -- technical_documentation
    -- declaration_of_conformity
    provision_type TEXT NOT NULL,

    -- Human/legal identifier where applicable.
    --
    -- Examples:
    -- 20
    -- 51
    -- 8
    -- 10
    provision_code TEXT,

    title TEXT,

    -- Full cleaned regulatory text used by
    -- the medical reasoning layer.
    text TEXT NOT NULL,

    -- Optional class explicitly associated
    -- with the provision.
    --
    -- Examples:
    -- I
    -- IIa
    -- IIb
    -- III
    device_class TEXT,

    -- Exact source provenance
    source_section TEXT,
    source_page INTEGER NOT NULL,
    source_excerpt TEXT,

    created_at TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ
        NOT NULL DEFAULT NOW(),

    CONSTRAINT medical_provisions_document_provision_unique
        UNIQUE (
            document_code,
            provision_id
        )
);


CREATE INDEX IF NOT EXISTS
    idx_medical_provisions_document
ON medical_provisions (
    document_code
);


CREATE INDEX IF NOT EXISTS
    idx_medical_provisions_type
ON medical_provisions (
    provision_type
);


CREATE INDEX IF NOT EXISTS
    idx_medical_provisions_code
ON medical_provisions (
    document_code,
    provision_code
);


CREATE INDEX IF NOT EXISTS
    idx_medical_provisions_class
ON medical_provisions (
    device_class
)
WHERE device_class IS NOT NULL;